[package]
name = "contracts"
version = "0.1.0"
edition = "2023_11"
cairo-version = "2.8.4"
scarb-version = "2.8.4"
description = "Cairo contracts for boostrapping a madara network."

[dependencies]
openzeppelin = "0.19.0"
openzeppelin_token = "0.19.0"

starknet = "2.8.4"

[[target.starknet-contract]]
sierra = true
casm = true
